require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'HuecosMed' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'HuecosMedTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  post_install do |installer|

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end

    #flipper_post_install(installer)
  end
end

target 'HuecosMed-tvOS' do
  # Pods for HuecosMed-tvOS

  target 'HuecosMed-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

#post_install do |pi|
#    pi.pods_project.targets.each do |t|
#      t.build_configurations.each do |config|
#        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
#      end
#    end
#end
